apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-microsservice
  namespace: mealrush
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-microsservice
  template:
    metadata:
      labels:
        app: content-microsservice
    spec:
      containers:
        - name: content-microsservice
          image: docker.io/lucascrapino/content-microsservice:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3025
          envFrom:
            - secretRef:
                name: auth-users-env
          resources:
            limits:
              memory: 256Mi
              cpu: 1
            requests:
              memory: 256Mi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: content-microsservice
  namespace: mealrush
spec:
  selector:
    app: content-microsservice
  ports:
    - protocol: TCP
      port: 3025
      targetPort: 3025
  type: NodePort