apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-microsservice
  namespace: mealrush
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-microsservice
  template:
    metadata:
      labels:
        app: food-microsservice
    spec:
      containers:
        - name: food-microsservice
          image: docker.io/lucascrapino/food-microsservice:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: auth-users-env
          resources:
            limits:
              memory: 256Mi
              cpu: 1
            requests:
              memory: 256Mi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: food-microsservice
  namespace: mealrush
spec:
  selector:
    app: food-microsservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort