apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-microsservice
  namespace: mealrush
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machine-microsservice
  template:
    metadata:
      labels:
        app: machine-microsservice
    spec:
      containers:
        - name: machine-microsservice
          image: docker.io/lucascrapino/machine-microsservice:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3010
          envFrom:
            - secretRef:
                name: auth-users-env
          resources:
            limits:
              memory: 256Mi
              cpu: 1
            requests:
              memory: 256Mi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: machine-microsservice
  namespace: mealrush
spec:
  selector:
    app: machine-microsservice
  ports:
    - protocol: TCP
      port: 3010
      targetPort: 3010
  type: NodePort