apiVersion: apps/v1
kind: Deployment
metadata:
  name: voucher-microsservice
  namespace: mealrush
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voucher-microsservice
  template:
    metadata:
      labels:
        app: voucher-microsservice
    spec:
      containers:
        - name: voucher-microsservice
          image: docker.io/lucascrapino/voucher-microsservice:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          envFrom:
            - secretRef:
                name: auth-users-env
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: voucher-microsservice
  namespace: mealrush
spec:
  selector:
    app: voucher-microsservice
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: NodePort
