name: voucher_microsservice
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  crypto: ^3.0.6
  dotenv: ^4.2.0
  mysql_client: 0.0.27
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  dart_amqp: ^0.3.1

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
